import { currentView } from "./state";
import { hidePrivacyPopup, initPrivacy } from "./modules/privacy";
import { initClock } from "./modules/clock";
import { initViewSwitcher, showOnlyView, syncCurrentView } from "./modules/view-switcher";
import { initLyricRenderer } from "./modules/lyric-renderer";
import { initMusicControls } from "./modules/music-controls";
import { initMinimizeDrag } from "./modules/minimize-drag";
import { initCapsuleInteraction } from "./modules/capsule-interaction";
import { initResizeObserver } from "./modules/resize-observer";
import { initNoticeQueue } from "./modules/notice-queue";
import { initCodexStatus } from "./modules/codex-status";
import { initQuickNote } from "./modules/quick-note";
import { initCapsuleExpansion } from "./modules/capsule-expansion";
import { initCodexQuota } from "./modules/codex-quota";

initClock();
initNoticeQueue();
initCodexStatus();
initCodexQuota();
initQuickNote();
initPrivacy();
initViewSwitcher();
initCapsuleExpansion();
initLyricRenderer();
initMusicControls();
initMinimizeDrag();
initCapsuleInteraction();
initResizeObserver();

showOnlyView("time");
hidePrivacyPopup();
void syncCurrentView(currentView);
